// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYR5NxF6B5ZY2VcNyK7-O7f5YrC7ZXvMU',
    appId: '1:631856390356:web:d1151fc0164ba69208db41',
    messagingSenderId: '631856390356',
    projectId: 'marketplace-se',
    authDomain: 'marketplace-se.firebaseapp.com',
    storageBucket: 'marketplace-se.appspot.com',
    measurementId: 'G-QRYMP0Z05S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaLjBEGjHQwohw-eoN2LGP71d8c0_pOnU',
    appId: '1:631856390356:android:a180152cd020392908db41',
    messagingSenderId: '631856390356',
    projectId: 'marketplace-se',
    storageBucket: 'marketplace-se.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd10igECr1ni4rQMWvcZJHwMxWmuLJ3xQ',
    appId: '1:631856390356:ios:281b3e23f5c1adfe08db41',
    messagingSenderId: '631856390356',
    projectId: 'marketplace-se',
    storageBucket: 'marketplace-se.appspot.com',
    iosClientId: '631856390356-3paqeigpqdmnpdiepsevndv3msjv5mg0.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd10igECr1ni4rQMWvcZJHwMxWmuLJ3xQ',
    appId: '1:631856390356:ios:ff99fada7aa0da5d08db41',
    messagingSenderId: '631856390356',
    projectId: 'marketplace-se',
    storageBucket: 'marketplace-se.appspot.com',
    iosClientId: '631856390356-monpn3d8mvpa06bbi82rsgtc6km0hq6r.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceFlutter.RunnerTests',
  );
}
